name: Build
on:
  push:
    branches: [ master ]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            BIN_SUFFIX:
          - os: macos-latest
            BIN_SUFFIX:
          - os: windows-latest
            BIN_SUFFIX: .exe
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Cache go module
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Setup vars
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: Build
        working-directory: ./cmd
        env:
          CGO_ENABLED: 0
        run: go build -trimpath -ldflags="-w -s" -v -o p2pNG-core ./cmd

      - name: Publish artifact
        uses: actions/upload-artifact@v1
        with:
          name: p2pNG-core_${{ runner.os }}_${{ steps.vars.outputs.short_sha }}{{matrix.BIN_SUFFIX}}
          path: ./cmd/p2pNG-core
        # todo: Use core-builder to build
